/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import DAOperations.DAO;
import UserToDb.to_db;
import java.awt.Color;
import java.awt.FlowLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author l.IsSaM.l
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public void init()  throws Exception{
        
        to_db.connect();
        this.setLocationRelativeTo(null);
        this.setSize(510, 400);
        LAY.setLayout(new FlowLayout());
       this.setLocationRelativeTo(null);
        UtilDateModel model = new UtilDateModel();
        model.setDate(2016, 01, 01);
        model.setSelected(true);
        JDatePanelImpl datePanel = new JDatePanelImpl(model, new Properties());
        datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());

        LAY.add(datePicker);
        LAY.setOpaque(true);
        LAY.setBackground(new Color(0, 0, 0, 0));

        listeSaler.setModel(new DefaultComboBoxModel(DAO.getAllSaler().toArray()));
        listeStore.setModel(new DefaultComboBoxModel(DAO.getStoresNameBySaler(1).toArray()));
    }

    public Ticket() throws Exception {
        initComponents();
        init();
      //    this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        listeSaler = new javax.swing.JComboBox();
        listeStore = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LAY = new javax.swing.JPanel();
        OK = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Saler");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 80, 100, 29);

        listeSaler.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listeSaler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeSalerActionPerformed(evt);
            }
        });
        listeSaler.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                listeSalerPropertyChange(evt);
            }
        });
        getContentPane().add(listeSaler);
        listeSaler.setBounds(140, 70, 270, 50);

        listeStore.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(listeStore);
        listeStore.setBounds(140, 160, 270, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Store");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setName(""); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 170, 100, 33);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  Date");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setName(""); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 260, 90, 33);

        LAY.setForeground(new java.awt.Color(236, 225, 116));

        javax.swing.GroupLayout LAYLayout = new javax.swing.GroupLayout(LAY);
        LAY.setLayout(LAYLayout);
        LAYLayout.setHorizontalGroup(
            LAYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        LAYLayout.setVerticalGroup(
            LAYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(LAY);
        LAY.setBounds(140, 260, 260, 50);

        OK.setText("Next");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(370, 320, 120, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHM/golden-ticket.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 0, 490, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listeSalerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_listeSalerPropertyChange
        
    }//GEN-LAST:event_listeSalerPropertyChange

    private void listeSalerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeSalerActionPerformed
 try{
    //  System.out.println(listeSaler.getSelectedItem().toString());

   listeStore.setModel(new DefaultComboBoxModel(DAO.getStoresNameBySaler(DAO.getId_salerByName(listeSaler.getSelectedItem().toString())).toArray()));// TODO add your handling code here:

 }catch(Exception e )
 {
     e.printStackTrace();
 }
    }//GEN-LAST:event_listeSalerActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
     try{
         this.setVisible(false);
         String dateOfTicket =  new SimpleDateFormat("YYYY-MM-dd HH:MM:ss").format( (Date) datePicker.getModel().getValue());
        new Category( listeSaler.getSelectedItem().toString() , listeStore.getSelectedItem().toString() , dateOfTicket).setVisible(true);    
        
    } catch(Exception e ) 
    {
        e.printStackTrace();
    }// TODO add your handling code here:
    }//GEN-LAST:event_OKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()  {
            public void run() {
                try{
                new Ticket().setVisible(true);
                }catch(Exception e )
                {
                    e.printStackTrace();
                }
            }
        });
    }
    private JDatePickerImpl datePicker;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LAY;
    private javax.swing.JButton OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox listeSaler;
    private javax.swing.JComboBox listeStore;
    // End of variables declaration//GEN-END:variables
}
